name: Build and Deploy Code

on: [push,pull_request]

jobs:
  Pulling-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Python linters Black Check
        uses: jose-lpa/python-black-check-action@1.0.0
