name: Build and Deploy Code

on: [push,pull_request]

jobs:
  Pulling-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Black Lint
        uses: jose-lpa/python-black-check-action@master
        with:
          path: '.'
          line-length: 80