name: Build and Deploy Code

on: [push,pull_request]

jobs:
  Pulling-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: install black
        run: pip install black==22.3.0
      - name: run black
        run: black . --check