name: Build and Deploy Code

on: [push,pull_request]

jobs:
  Pulling-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: install Python version 3.9
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v2
        with:
          python-version: '3.9' 
      # - run: python main.py
      - name: update Pip
        run: Python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
        