name: Build and Deploy Code

on: [push,pull_request]

jobs:
  Pulling-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: install Python version
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - run: python my_script.py